### ISSUE TITLE
Reproduce simulation for help

### ISSUE THREAD

**Issue by 17336320859** [Wenqi-Cui/RNN-RL-Frequency-Lyapunov#1]
Your honor

Hello, I am trying to reproduce the simulation in this article, but I don't know the python version used in your simulation, and what packages are used and the versions of these packages, please let me know? Just to learn, thank you!

LiuZheng

**Comment by Wenqi-Cui** [comment]
Hi Zheng,

Thanks for your attention. The python version is 3.8.16 and the TensorFlow version is Tensorflow 2.0. Other packages such as NumPy can be found from the blocks of import, and the latest version should be fine. 

Best wishes,

Wenqi

**Comment by Wenqi-Cui** [comment]
Hi Zheng,

I have updated the code with [a link ](https://colab.research.google.com/drive/1vinnX16zuRR0I13ofpopk61zFeTMfwbK?usp=sharing)that can be directly run using  Google Colab. The Colab is free and it can eliminate lots of effort in environment setup. I'll close this comment and please feel free to let me know if you have any other questions.

Best wishes,

Wenqi
